2021-05-25 00:09:05,399 ERROR: Exception on / [POST] [in c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\acer\microblog\app\routes.py", line 14, in index
    post=Post(body=form.post.data,author=current_user)
NameError: name 'Post' is not defined
2021-05-25 00:09:51,883 INFO: Microblog startup [in C:\Users\acer\microblog\app\__init__.py:41]
2021-05-25 00:29:33,188 INFO: Microblog startup [in C:\Users\acer\microblog\app\__init__.py:41]
2021-05-25 00:29:35,176 ERROR: Exception on / [GET] [in c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\acer\microblog\app\routes.py", line 20, in index
    return render_template('index.html',title="home page",form=form,posts=posts)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\acer\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\acer\microblog\app\templates\base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\acer\microblog\app\templates\index.html", line 18, in block "content"
    {% include '_post.html' %}
  File "C:\Users\acer\microblog\app\templates\_post.html", line 4, in top-level template code
    <img src="{{ post.author.avatar(36) }}">
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'post' is undefined
2021-05-25 00:33:06,221 INFO: Microblog startup [in C:\Users\acer\microblog\app\__init__.py:41]
2021-05-25 00:33:07,790 ERROR: Exception on / [GET] [in c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\acer\microblog\app\routes.py", line 20, in index
    return render_template('index.html',title="home page",form=form,posts=posts)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\acer\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\acer\microblog\app\templates\base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\acer\microblog\app\templates\index.html", line 18, in block "content"
    {% include '_post.html' %}
  File "C:\Users\acer\microblog\app\templates\_post.html", line 4, in top-level template code
    <img src="{{ post.author.avatar(36) }}">
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'post' is undefined
2021-05-25 00:33:35,410 ERROR: Exception on / [GET] [in c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\acer\microblog\app\routes.py", line 20, in index
    return render_template('index.html',title="home page",form=form,posts=posts)
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\acer\microblog\.venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\acer\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\acer\microblog\app\templates\base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\acer\microblog\app\templates\index.html", line 18, in block "content"
    {% include '_post.html' %}
  File "C:\Users\acer\microblog\app\templates\_post.html", line 4, in top-level template code
    <img src="{{ post.author.avatar(36) }}">
  File "c:\users\acer\microblog\.venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'post' is undefined
2021-05-25 00:33:59,035 INFO: Microblog startup [in C:\Users\acer\microblog\app\__init__.py:41]
